version: '3.9'
services:
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - /opt/grafana-influxdb/grafana:/var/lib/grafana

  influxdb:
    image: influxdb:1.8.10
    container_name: influxdb
    ports:
      - 8086:8086
    volumes:
      - /opt/grafana-influxdb/influxdb:/var/lib/influxdb

volumes:
  grafana:
  influxdb: